[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.30'
auto_detect_remappings = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@solady/=lib/solady/src/",
    "@solady-test/=lib/solady/test/"
]

[fuzz]
runs = 2048